version: '3.1'
services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
     - db-v:/var/lib/postgresql/data
    ports:
     - '5432:5432'
    environment:
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: shalala
     POSTGRES_DB: spotigram-db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
     - pgadmin-v:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: emindvf@mail.com
      PGADMIN_DEFAULT_PASSWORD: shalala
    ports:
     - "5000:80"

volumes:
  db-v:
  pgadmin-v: 
