version: '3.1'
services:
  nosqldb:
    image: cassandra:5.0-jammy
    restart: always
    volumes:
     - nosqldb-v:/var/lib/cassandra
    ports:
     - "9042:9042"
    environment:
     CASSANDRA_CLUSTER_NAME: spotigram-cluster
     
  sqldb:
    image: postgres:alpine
    restart: always
    volumes:
     - sqldb-v:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    environment:
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: shalala
     POSTGRES_DB: spotigram-db
    
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-v:/data
  
volumes:
  nosqldb-v:
  sqldb-v:
  redis-v: 
