app:
  server:
    port: 8080
    request_size_limit: 1048576000

sql_database:
  host: localhost
  port: 5432
  user: admin
  password: shalala
  dbname: spotigram-db
  sslmode: disable
  timezone: EET
  init_table_script_path: ./scripts/sql/postgres-table-setup.sql

cql_database:
  host: localhost
  port: 9042
  keyspace: spotigram
  init_keyspace_script_path: ./scripts/cql/cassandra-keyspace-setup.cql
  init_table_script_path: ./scripts/cql/cassandra-table-setup.cql

cache:
  redis_url: localhost:6379

access_token:
  private_key_path: ./configs/keys/key.priv
  public_key_path: ./configs/keys/key.pub
  expires_in: 240h
  max_age: 15

refresh_token:
  private_key_path: ./configs/keys/key.priv
  public_key_path: ./configs/keys/key.pub
  expires_in: 240h
  max_age: 15